Greeting.create(text: 'Hey there, have a day full of joy!')
Greeting.create(text: 'Enjoy your day to the fullest and savor every moment.')
Greeting.create(text: 'Hi, wishing you a day full of positive energy!')
Greeting.create(text: 'Wishing you a wonderful day filled with happiness.')
Greeting.create(text: "It's a new day, make it a fantastic one!")
